export * from "./validators/academic";
export * from "./validators/attendance";
export * from "./validators/extracurricular";
export * from "./validators/journal";
export * from "./validators/lhbs";
export * from "./validators/schedule";
export * from "./validators/spp";
export * from "./types";
export * from "./validators/ppdb";
